project:
  type: website

website:
  title: "Datafantic"
  description: "Uncovering the data behind everything"
  twitter-card:
    creator: "@RobertERitz"
  open-graph:
    site-name: Datafantic
  site-url: https://datafantic.com
  favicon: "images/favicon.png"
  navbar:
    title: false
    logo: "images/logo.png"
    logo-alt: "Datafantic"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/RobertERitz
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/datafantic/datafantic-website

format:
  html:
    theme: litera
    css: styles.css
    toc: true



